# Generated by Django 4.2.3 on 2023-07-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-category'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
